language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
#
before_install:
  - sudo apt-get install libevent-dev
  - pip install -r tests-requirements.txt --use-mirrors

install:
  - python setup.py install


# command to run tests
script:
    - "nohup python tests/server.py &"
    - "python tests/client.py"